### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by stefanpantic** [MATF-RG17/RG061-find-your-way#2]
Postovani, 

Rekli ste da Vam napomenem ako biste mogli da mi date savete/primedbe vezane za C++ deo projekta.
Unapred zahvaljujem.

Stefan Pantic 429/2016

**Comment by ivan-cukic-matf** [comment]
- Čemu služi klasa Hub - sve u njoj je static (video sam kasnije... neobičan pristup, ali nije loša ideja);
- View::look_at ima dve razlicite semantike u zavisnosti od toga da li se poziva sa ili bez argumenata. Uz to, look_at() moze da bude `const`;
- Geteri u C++-u obično nemaju `get` prefix;
- Nemojte da prefiksujete privatne funkcije donjim crtama (pajton konvencije nisu preterano popularne u C++-u :) );
- `draw` funkcija ne bi trebalo da ima i ažuriranje pozicije - iscrtavanje treba da bude `const` članska funkcija - brzina kretanja ne treba da zavisi od brzine iscrtavanja;
- `colision` -> `collision` :)
- Mogli ste da definisete alias i za pair<Move, Move>

Sve u svemu, lepo odradjeno, nema nekih bitnijih zamerki.
